blog/urls.py
"""
Created on 2018/2/22
@Author: Jeff Yang
"""

from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$', views.index),  # ^$分别限制开头和结尾，即限定为空
    url(r'^index/$', views.index, name='index'),  # 限制index，注意加一个‘/’，否则访问“http://localhost:8000/blog/index/”会出现404
    # 把匹配到的数字以article_id作为组名，组名必须和响应函数的参数名一致，否则会报错
    url(r'^article/(?P<article_id>[0-9]+)/$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)/$', views.edit_page, name='edit_page'),
    url(r'^edit/action/$', views.edit_action, name='edit_action'),
]

blog2/urls.py
"""
Created on 2018/2/22
@Author: Jeff Yang
"""

from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$', views.index),  # ^$分别限制开头和结尾，即限定为空
    url(r'^index/$', views.index),  # 限制index，注意加一个‘/’，否则访问“http://localhost:8000/blog/index/”会出现404
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# import blog.views as bv

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^index/', bv.index),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^blog2/', include('blog2.urls')),
]

blog/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')  # 必选参数max_length
    content = models.TextField(null=True)  # 没有必选参数
    # pub_time = models.DateTimeField(auto_now=True)  # auto_now意思是创建对象时自动设置为当前时间
    pub_time = models.DateTimeField(null=True)

    def __str__(self):
        """Python语法，用于显示这个类的实例对象打印出来的效果"""
        return self.title

blog2/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from . import models


# def index(request):
#     return HttpResponse("Hello, World!")

def index(request):
    # article = models.Arcticle.objects.get(pk=1)  # 获取主键值为1的文章
    articles = models.Article.objects.all()  # 获取所有文章
    return render(request, 'blog/index.html', {'articles': articles})  # 第二个参数是相对templates目录的路径


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':  # ID是从1开始的，所以新建文章时传入0
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'TITLE')  # 也可以用request.POST['title']，这里的TITLE为默认值
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id', '0')

    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        # articles = models.Arcticle.objects.all()
        # return render(request, 'blog/index.html', {'articles': articles})
        # 新建博客成功后会跳转到首页，这时浏览器里地址还是指向刚才的提交表单地址http://localhost:8000/blog/edit/action/
        # 这时候刷新页面，会再多添加一条数据。
        # 改成以下语句重定向
        return HttpResponseRedirect('/blog/index')
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, 'blog/article_page.html', {'article': article})

blog2/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'blog2/index.html', {'hello': 'Hello, Blog2!!'})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/><br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
<a href="{% url 'blog:index' %}">返回文章列表页</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    <!--出于安全性，POST请求都需要加这句话，否则会报错403-->
    {% csrf_token %}
    {#        {% if article %}#}
    {#            <input type="hidden" name="article_id" value="{{ article.id }}"/>#}
    {#            <label>文章标题：#}
    {#                <input type="text" name="title" value="{{ article.title }}"/>#}
    {#            </label>#}
    {#            <br/><br/>#}
    {#            <label>文章内容：#}
    {#                <input type="text" name="content" value="{{ article.content }}"/>#}
    {#            </label>#}
    {#            <br/><br/>#}
    {#        {% else %}#}
    {#            <input type="hidden" name="article_id" value="0"/>#}
    {#            <label>文章标题：#}
    {#                <input type="text" name="title"/>#}
    {#            </label>#}
    {#            <br/><br/>#}
    {#            <label>文章内容：#}
    {#                <input type="text" name="content"/>#}
    {#            </label>#}
    {#            <br/><br/>#}
    {#        {% endif %}#}
    {#        <input type="submit" value="提交">#}

    {# 注意0左右不要有空格，否则会一起传值到后台 #}
    {#    <input type="hidden" name="article_id" value="{% if article %}{{ article.id }}{% else %}0{% endif %}"/>#}
    {#    <label>文章标题：#}
    {#        <input type="text" name="title" value="{% if article %}{{ article.title }}{% endif %}"/>#}
    {#    </label>#}
    {#    <br/><br/>#}
    {#    <label>文章内容：#}
    {#        <input type="text" name="content" value="{% if article %}{{ article.content }}{% endif %}"/>#}
    {#    </label>#}
    {#    <br/><br/>#}
    {#    <input type="submit" value="提交">#}

    {# 如果模版中出现了不存在的变量，Django不会报错，只会给一个空值 #}

    <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}"/>
    <label>文章标题：
        <input type="text" name="title" value="{{ article.title }}"/>
    </label>
    <br/><br/>
    <label>文章内容：
        <input type="text" name="content" value="{{ article.content }}"/>
    </label>
    <br/><br/>
    <input type="submit" value="提交">

</form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">新增文章</a>
</h1>
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br/><br/>
{% endfor %}
</body>
</html>

blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
<h1>This is Blog2!</h1>
<h1>{{ hello }}</h1>
</body>
</html>